### PR TITLE
Enable to process URIs like openhab://?item=test&command=ON

### PR DESCRIPTION
**Pull request by cribskip**
This makes use of the nfc-Handler and enhances it with handling of shortcut-handling. F.e. one can now put a shortcut on the home screen and change an items state just like the NFC tag would do - besides auto-generation of the URI ;)

### CODE REVIEW

**Comment by eschava** [comment]
Wow! Looks cool

**Comment by cribskip** [comment]
My branch is now ahead and behind master branch so I see
```
Add more commits by pushing to the URI-Handler branch on cribskip/openhab.android.

This pull request contains merge conflicts that must be resolved.
Only those with write access to this repository can merge pull requests.
```

How do I fix this? ... don't want to re-fix my repos ;)
Additionally, I added a little documentation on https://github.com/cribskip/openhab.android/wiki. How do I commit these?

Thanks :)

**Comment by kaikreuzer** [comment]
You should rebase your branch onto the lastest master. Would be great if we could get this feature in this weekend (@belovictor, any chance for this?) as I would like to use it in my IoT workshop next week!

**Comment by cribskip** [comment]
Well, I'm not on my dev-env this weekend, sorry. If someone else could implement the changes, that would be just fine 😊

**Comment by cribskip** [comment]
Could not get my branch to rebase to upstream so created a new pull request, please see #78. Very sorry to spam :-(

**Pull request closed without merging**
