### PR TITLE
Right align spinner items

### LINKED ISSUE #439: Selection Items should be right justified
As per the discussion in #290 I am opening a new issue on the selection items needing to be right justified. 

Presently the items are not right justified and therefore don't line up correct, see picture below:
image

### PR DESCRIPTION
**Pull request by boc-tothefuture**
This resolves #439

### CODE REVIEW

**Comment by boc-tothefuture** [comment]
@mueller-ma  - Patch applied.

**Comment by boc-tothefuture** [comment]
@mueller-ma 
 Did this ever work for you?  I am pretty sure it worked for me - but after everything was merged to Master my items are no longer right aligned.   Trying to verify it was in fact working at some point to assist with trouble shooting.

**Comment by mueller-ma** [comment]
Yes, it worked for me, but also doesnt work on openhab/master

**Comment by mueller-ma** [comment]
#436 broke it, but I think I found a fix

**Pull request merged**
