### PR TITLE
Update Russian translation

### PR DESCRIPTION
**Pull request by jvitkauskas**
Update translation after #337 was merged

### CODE REVIEW

**Comment by mueller-ma** [comment]
There are some missing strings in the Russian translation. See #374 and #389, maybe some other as well.

**Comment by jvitkauskas** [comment]
Hi, I have translated missing strings now.

**Comment by mueller-ma** [comment]
Can you remove the following strings as they aren't used anymore?
settings_openhab_username_summary
settings_openhab_password_summary
error_authentication_failed
erorr_no_wifi_state_permission
erorr_no_wifi_mcast_permission

**Comment by jvitkauskas** [comment]
Yes, see updated commit

**Comment by digitaldan** [comment]
Thanks!

**Pull request merged**
