### PR TITLE
Support HTTPS with client certificate authentication

### LINKED ISSUE #109: Support HTTPS with client certificate authentication.
We can simply terminate https with client certificate authentication by haproxy or stunnel. If you wish I can show this configuration for those application.

Such configurations can be next security level for private openhab installation.
We need support for https with client certificate authentication by android application.

On android system we can import CA and personal certificate to system certificate store.  It will be good if application can use this.
##

### PR DESCRIPTION
**Pull request by slawekjaranowski**
Fix #109

My proposition to support ssl client certificate

### CODE REVIEW

**Comment by slawekjaranowski** [comment]
#158 is still needed and #159 will be useful

**Comment by digitaldan** [comment]
Hi @slawekjaranowski , I'm planning on reviewing this next, thanks.

**Comment by slawekjaranowski** [comment]
@digitaldan thanks, I will rebese code with the latest master version.

**Comment by digitaldan** [comment]
So I tested the new setting menu and existing functionality, but i will trust that the actual key based authentication works.  How would you suggest such a feature be explained to users?  Since neither OH1 or OH2 has key based auth, this feature will not immediately be obvious on how to use.  I would suggest creating a markdown/wiki page in the project describing how this is used.  It would also be nice if there was somewhere in that menu setting that directed the user to that page. 

Due to another check in, this will need to have conflicts resolved :-(

**Comment by slawekjaranowski** [comment]
Where I should put page with manual? In wiki of android app or in other wiki?
If it posible please create empty page - i will put some content.
I will also try to implement links to page from configurations.

As I know OH2 doesn't support any authorization - maybe I'm wrong.

**Comment by digitaldan** [comment]
I would add something like KeyAuth.md to this repo and add the instructions there (just create it and check it in).  We can then add that info to the main openHAB wiki.  

OH2 auth functionality is still being designed, there is talk about going oauth, not sure where that stands at the moment.

**Comment by Br3nda** [comment]
useful feature. keen to test for you when the merge conflicts are resolved. Some tests for this feature would make this PR super sparkly.

**Comment by digitaldan** [comment]
Closing due to inactivity,

**Pull request closed without merging**
