### PR TITLE
change google play badge height

### PR DESCRIPTION
**Pull request by mueller-ma**
Signed-off-by: mueller-ma <mueller-ma@users.noreply.github.com>

### CODE REVIEW

**Comment by FlorianSW** [comment]
Could you explain why? :/

**Comment by mueller-ma** [comment]
Imo it is better readable

**Comment by FlorianSW** [comment]
Makes sense! :) +1

**Comment by tsheldon** [comment]
Just a side note, but the trademark disclaimer should read "Google Play and the Google Play logo are trademarks of Google Inc."

See the requirements posted on https://play.google.com/intl/en_us/badges/

**Comment by mueller-ma** [comment]
The Readme says: "Product names, logos, brands and other trademarks referred to within the openHAB website are the property of their respective trademark holders. These trademark holders are not affiliated with openHAB or our website. They do not sponsor or endorse our materials."

**Comment by tsheldon** [comment]
Yes, I saw that.   My note is regarding the actual text-  per the guidelines page:

Any use of the Google Play name in your marketing or communications must be accompanied by a legal attribution footer stating: “Google Play and the Google Play logo are trademarks of Google Inc.”

**Pull request merged**
