### PR TITLE
MultiDex support

### LINKED ISSUE #147: MultiDex support for pre-lollipop devices
I've been coding Android apps for a few years now using Eclipse.  I pulled and built openhab.android last night using Android Studio.  It built nicely for my devices running Lollipop, but Android 4.X devices require some tweaks as described in Nicolas Tyler's answer here:

http://stackoverflow.com/questions/26925264/android-support-multidex-library-implementation

I have this working now for Android 4.X devices with multidex support, but wanted to create a ticket before checking this in.  I believe it will be helpful for newer developers hoping to contribute.

### PR DESCRIPTION
**Pull request by slawekjaranowski**
Fix #147, #155

### CODE REVIEW

**Comment by slawekjaranowski** [comment]
Similar commit is also in: #154

**Comment by CristianSarac** [comment]
This should be merged to the master branch so that not all other PR have to come bundled with this, that is if we plan on supporting android versions prior to Android 5.0

**Comment by digitaldan** [comment]
Hi @slawekjaranowski , thank you for the PR! I just ran this on a 4.x simulator and a 5.x phone and all seems to be working.  One last thing, can you modify your commit message as stated in https://github.com/openhab/openhab-distro/blob/master/CONTRIBUTING.md ?

**Comment by slawekjaranowski** [comment]
Hi @digitaldan  - hhat exactly is missing in my commit message?

**Comment by digitaldan** [comment]
Sorry I was not very clear, in the contributing agreement above please read the section under 'Sign your work', if you agree to those terms, modify your commit message (git commit --ammend) and add your signature, the example used in that section looks like: "Signed-off-by: Joe Smith <joe.smith@email.com> (github: github_handle)"  .  I have added my name and email to my .gitconfig file so when I do commits i only have to pass '-s' to git and it will do this automatically for me. 
.gitconfig
```[user]
	name = Dan Cunningham
	email = dan@digitaldan.com
```

**Comment by slawekjaranowski** [comment]
This commit and other my PR already has proper "Signed-off-by" line, please check.

**Comment by digitaldan** [comment]
@slawekjaranowski , apologies, I was looking in the wrong place and did not see you signature.  Sorry for the confusion!

**Comment by slawekjaranowski** [comment]
@digitaldan no problem, I think that #155 also can be closed.

**Comment by kaikreuzer** [comment]
@digitaldan When merging, I suggest adding the PRs to a milestone (currently 1.8.0 set up) - so that we can easily have release notes when publishing a new version to the PlayStore.

**Comment by digitaldan** [comment]
Thanks Kai, I will do that going forward.

**Pull request merged**
