### PR TITLE
Update Lithuanian, Russian translations

### PR DESCRIPTION
**Pull request by jvitkauskas**

### CODE REVIEW

**Comment by mueller-ma** [comment]
info_openhab_gcm_connected in values-lt needs the parameter `%s`. Can you add that?

**Comment by jvitkauskas** [comment]
Fixed

**Comment by jvitkauskas** [comment]
Ok. Done that.

**Comment by mueller-ma** [comment]
@jvitkauskas Can you please [sign](https://github.com/openhab/openhab.android/blob/master/CONTRIBUTING.md#sign-your-work) your commit?

**Comment by jvitkauskas** [comment]
Done

**Pull request merged**
