### PR TITLE
Create code of conduct

### PR DESCRIPTION
**Pull request by mueller-ma**
Github suggest to add a code of conduct and I also think its a good idea. In line 37 I had to insert a mail address. Is that one ok or does another one suit better?

### CODE REVIEW

**Comment by digitaldan** [comment]
@kaikreuzer this probably is something we would want to do across all projects or not as all?  Thoughts?

**Comment by mueller-ma** [comment]
@kaikreuzer Poke

**Comment by kaikreuzer** [comment]
Sorry @mueller-ma, I didn't see this before.

> this probably is something we would want to do across all projects or not as all? 

Correct and we actually have that in place over almost all projects as a part of the CONTRIBUTING.md see e.g. https://github.com/openhab/openhab-distro/blob/master/CONTRIBUTING.md#community-guidelines. Interestingly, this section has been left away in this repo here, don't ask me why 😟 

We also have this in the central developer documentation, see https://docs.openhab.org/developers/contributing/contributing#community-guidelines.

I'd therefore suggest to align the Android repo with the others (and if you feel that these guidelines are missing anything essential, let's first discuss this in the forum under the "code" section).

**Comment by mueller-ma** [comment]
Ok, I will add the community guidelines to this repo.

**Pull request closed without merging**
