### PR TITLE
Fix up GCM status printing.

### PR DESCRIPTION
**Pull request by maniac103**
Use the string formatting built into getString(), and don't print the ID
if it's known to be null anyway.

Signed-off-by: Danny Baumann <dannybaumann@web.de>

### CODE REVIEW

**Comment by maniac103** [comment]
Unfortunately I had to remove the respective translations for Greek and Russian as my understanding of those languages isn't good enough for adapting the string :-(

@edgiru @karafyllidis Can you please help me out there?

**Comment by mueller-ma** [comment]
What about german?

**Comment by maniac103** [comment]
> What about german?

values-de doesn't have a translation for this string yet; I'll add it in a follow-up PR as mentioned in https://github.com/openhab/openhab.android/pull/337#issuecomment-335075561

**Comment by digitaldan** [comment]
>Unfortunately I had to remove the respective translations for Greek and Russian as my understanding of those languages isn't good enough for adapting the string :-(

Can you ask in the forums for translation help with that?

**Comment by karafyllidis** [comment]
@digitaldan @maniac103 I can help with the Greek translation. What you need in Greek is the following
<string name="info_openhab_gcm_not_connected">Η εγγραφή συσκευής απέτυχε</string>

**Comment by maniac103** [comment]
@karafyllidis Thanks! That leaves us with the Russian string.

**Comment by karafyllidis** [comment]
@maniac103 Anytime. Sorry for the delay

**Comment by jvitkauskas** [comment]
Please see updated Russian and Lithuanian translations here: https://github.com/jvitkauskas/openhab.android/commit/241fc89da95b0bd1a560b144922439e7a397b7b4

**Comment by jvitkauskas** [comment]
Also, shouldn't "theme_value_light", "theme_value_dark" and "theme_value_black" be marked non-translatable?

**Comment by maniac103** [comment]
@jvitkauskas Thanks! Will add your commit to this PR.

> BTW, shouldn't "theme_value_light", "theme_value_dark" and "theme_value_black" be marked non-translatable?

Yes, I'd think so.

**Comment by maniac103** [comment]
The code side of this is merged via #337 now, but the strings are left out. @karafyllidis @jvitkauskas Should I submit a PR with your translation additions or will you do it?

**Comment by karafyllidis** [comment]
@maniac103 I have just submitted PR #413 for the Greek translation

**Pull request closed without merging**
