### PR TITLE
Scale images to be fully visible

### PR DESCRIPTION
**Pull request by lolodomo**
Signed-off-by: Laurent Garnier <lg.hc@free.fr>

### CODE REVIEW

**Comment by lolodomo** [comment]
This PR allows having images fully visible on the tablet/phone. Before this PR, for example the music album arts with their square resolution were scaled in such a way that you can't show them fully (height was to much important) when the tablet was in landscape mode.

**Comment by lolodomo** [comment]
Why 95% ?

PS: it is very easy to adjust.

**Comment by mueller-ma** [comment]
So you dont have to scroll at exactly that pixel where you can see the complete picture.

**Comment by mueller-ma** [comment]
It doesnt have to be 95%, just an idea. When you change something, please do not force push, so everyone can see the changes after my review.

**Comment by lolodomo** [comment]
Change done, the max height of an image is set to 90%. It allows seeing another row of data.

**Comment by lolodomo** [comment]
I merged with the master branch to resolve the conflict introduced by the merge of my PR 481.

**Pull request merged**
