### PR TITLE
Add splash screen

### PR DESCRIPTION
**Pull request by mueller-ma**
This PR adds a screen with the openhab logo on startup.

### CODE REVIEW

**Comment by maniac103** [comment]
https://medium.com/@ssaurel/create-a-splash-screen-on-android-the-right-way-93d6fb444857

(There's also similar posts by Android developers themselves, but I seem to be unable to find them at the moment)

An intermediate activity has the downside of
- longer load times
- unexpected navigation if you navigate away from the splash screen

**Comment by maniac103** [comment]
Oops, I should have read that link that I quickly dug out - it also uses that intermediate activity. I'll look further, I'm pretty sure there's a way without that.

**Comment by mueller-ma** [comment]
@maniac103 Can you have a look at my latest commit? I dont see the splash screen comming up

**Comment by mueller-ma** [comment]
Thanks. Can you see my commit?

**Pull request merged**
