### PR TITLE
Second try to fix #121 and #359

### LINKED ISSUE #121: Switch label and item text overlaps if too many mappings defined
For a chart, I am using a switch item with 4 mappings:

```
Group item=Humidity label="Luftfeuchtigkeit" {
      Switch item=HumidityChartPeriod label="Zeitraum" mappings=[0="Stunde", 1="Tag", 2="Woche", 3="Monat"]
      Chart item=HumidityChart period=4h refresh=60000 visibility=[HumidityChartPeriod==0]
      Chart item=HumidityChart period=D refresh=60000 visibility=[HumidityChartPeriod==1, HumidityChartPeriod=="Uninitialized"]
      Chart item=HumidityChart period=W refresh=60000 visibility=[HumidityChartPeriod==2]
      Chart item=HumidityChart period=M refresh=60000 visibility=[HumidityChartPeriod==3]
    }
```

On my Nexus 4, the label of the switch item overlaps with the mappings:
switchitem

Would be nice if there was some solution where texts don't overlap
##

### PR DESCRIPTION
**Pull request by mueller-ma**
screenshot_2017-10-01-22-18-57

Signed-off-by: mueller-ma <mueller-ma@users.noreply.github.com>

### CODE REVIEW

**Comment by FlorianSW** [comment]
Wouldn't it be possible to wrap the content of the widget name and fill out multiple lines?

**Comment by mueller-ma** [comment]
Note that the screenshot was taken on a tablet. On my smartphone there isn't enough place for a second line (I think).

**Comment by digitaldan** [comment]
So this is hard for me to test, and since it's since it's all layout logic, hard to read and know exactly what it's doing. So, my question is, are you comfortable with me merging this and it going out to users, or do you need time to better perfect it?  I understand how difficult GUI alignment issues can be.

**Comment by mueller-ma** [comment]
I'm sure, that this solution is way better than the previous fix. I have some trouble connecting virtual devices to my own oh server, so I have only tested it on my low res tablet. Dan, can you show a screenshot like in the previous fix?

**Comment by digitaldan** [comment]
Sounds good, I will test tomorrow and merge if all looks ok.

**Pull request merged**
