### PR TITLE
Md appcompat

### PR DESCRIPTION
**Pull request by Human**
I switched to AppCompat instead of the native Material support. This should work perfectly for Lollipop devices and provide some MD support for pre-Lollipop builds, as old as ICS.

### CODE REVIEW

**Comment by belovictor** [comment]
This pull request can't be merged. The code of the app was migrated to appcompat for the Material UI migration some time ago already though.

**Comment by vevo-bob-igo** [comment]
>The code of the app was migrated to appcompat for the Material UI migration some time ago already though.

Looks like it was changed 10 days ago, and my PR was from 18 days ago. Oh well, at least it's finally done.

**Comment by Human** [comment]
(Sorry, I previously commented as the wrong "me.")

>The code of the app was migrated to appcompat for the Material UI migration some time ago already though.

I authored my change 18 days ago, and it looks like you had a commit 10 days ago that overlapped it. In any case, I'm glad that it's using appcompat now.

In the future, how can I know what issues are being worked on, to avoid spending time doing something that will later be made obsolete?

**Comment by belovictor** [comment]
Hi,
I'm sorry it was a waste of time for you, I was working on this code for a month or so :-)
The best way is to create an issue describing a feature you want to contribute as described in https://github.com/openhab/openhab.android/blob/master/CONTRIBUTING.md before writing the code!
Then it can be effectively discussed by all interested parties and there will be no duplicates and time wasting! :-)

**Comment by kaikreuzer** [comment]
Would you be able to do the same @belovictor, so that others can see what it in the pipeline from your end?

**Comment by Human** [comment]
I did look at the issues here in github and didn't see anything related to appcompat or material design. Why require someone to go outside of github to see what issues are being worked on for the github project?

It only took me about 2 hours, anyway, so it's not like I lost days of work. Frankly, it does discourage me from contributing more changes, though.

**Comment by belovictor** [comment]
@kaikreuzer , true, it is my fault, I just got used that there were no external contributions for 2 years :-(
@Human , what do you mean by "outside of github"? I exactly meant github issues, contribution guide also points to github issues. I understand your discouragement, and this is completely my fault. As I stated already, there were no external contributions to Android app for 2 years, so I got used to develop it on my own. Time to change my behaviour on that!

**Comment by kaikreuzer** [comment]
> @kaikreuzer , true, it is my fault, I just got used that there were no external contributions for 2 years :-(

I clearly understand where this behavior comes from, I fall into it myself when I am almost the only one working on some project. But I think it is a great sign of success to have more and more people contributing to HABDroid now and so attitudes need to adapted :-)

**Comment by Human** [comment]
I understand completely, @belovictor. If you promise to make an issue for any code changes you're working on, I'll help out again when I get the time. Sound good?

**Comment by belovictor** [comment]
Sounds great. I made 4 of them already :-)

**Pull request closed without merging**
