### PR TITLE
Change dark theme

### PR DESCRIPTION
**Pull request by mueller-ma**
I changed the primary color in the dark theme to the openhab orange
screenshot_2017-05-20-11-52-57
screenshot_2017-05-20-12-34-09

### CODE REVIEW

**Comment by digitaldan** [comment]
I always like to get @kaikreuzer opinions on UI changes like this, as he always has a (valid) opinion :-)  @kaikreuzer for your reference this changes the "Dark" theme from using a Light/Med Grey header to OH orange.  I'm not sure how many are using the dark theme on things like wall tablets where maybe the orange would not be welcomed.  Thoughts?

**Comment by mueller-ma** [comment]
@digitaldan I have thought about wall mounted tablets:
1. I think something like habpanel is more suitable for tablets.
2. We could add more themes with several material colors

**Comment by mueller-ma** [comment]
Maybe one for each of these: https://material.io/guidelines/style/color.html#

**Comment by kaikreuzer** [comment]
Afair, @belovictor chose the grey header at the time as he wanted something "not bright" for the dark theme - the orange color somehow undermines this idea. So I think it would be the better idea to introduce additional themes instead of changing existing ones.

**Comment by mueller-ma** [comment]
You're right. I wanted to keep the "identity" with the orange, but it is too bright. I will close this.

**Pull request closed without merging**
