### PR TITLE
Replace png images for navigation drawer with Vector drawable equivalent

### PR DESCRIPTION
**Pull request by FlorianSW**
Vector drawables scales better on different sizes and looks lees fuzzy
when they are resized.

This also allows us to have different color for the icons in different
themes much more easily.

### CODE REVIEW

**Comment by FlorianSW** [comment]
Some images for comparsion from my HTC 10:
Before:
screenshot_20171029-184414

After:
screenshot_20171029-183958

**Comment by mueller-ma** [comment]
Can you also replace the microphone in the action bar with a svg? And does svg have any minimum api level?

**Comment by FlorianSW** [comment]
Done! :)

**Comment by mueller-ma** [comment]
Can you also remove the unused customMic attribute from the themes?

**Pull request merged**
