### PR TITLE
Fix overlapping item label and selection switch

### LINKED ISSUE #121: Switch label and item text overlaps if too many mappings defined
For a chart, I am using a switch item with 4 mappings:

```
Group item=Humidity label="Luftfeuchtigkeit" {
      Switch item=HumidityChartPeriod label="Zeitraum" mappings=[0="Stunde", 1="Tag", 2="Woche", 3="Monat"]
      Chart item=HumidityChart period=4h refresh=60000 visibility=[HumidityChartPeriod==0]
      Chart item=HumidityChart period=D refresh=60000 visibility=[HumidityChartPeriod==1, HumidityChartPeriod=="Uninitialized"]
      Chart item=HumidityChart period=W refresh=60000 visibility=[HumidityChartPeriod==2]
      Chart item=HumidityChart period=M refresh=60000 visibility=[HumidityChartPeriod==3]
    }
```

On my Nexus 4, the label of the switch item overlaps with the mappings:
switchitem

Would be nice if there was some solution where texts don't overlap
##

### PR DESCRIPTION
**Pull request by mueller-ma**
I have tested this on a tablet. but it may need some testing on a smartphone.
screenshot_2017-09-05-18-46-41
Fixes #121 and #359 
Signed-off-by: mueller-ma <mueller-ma@users.noreply.github.com>

### CODE REVIEW

**Comment by digitaldan** [comment]
So I'm testing this and getting mixed results on my tester phone (nexus 6).  I'm not sure its worse, but its its still overlapping and making the layout odd in a different way, I have some screenshots I will try and post.

**Comment by mueller-ma** [comment]
The problem is that for some reasons my virutall devices wont connect to openhab, so I cannot test it

**Comment by digitaldan** [comment]
I'm going to merge if this at least helps on a tablet.

**Comment by mueller-ma** [comment]
Ok, but please reopen the issue.

**Pull request merged**
