### PR TITLE
Add material icon

### LINKED ISSUE #278: Material icon
I'm using this icon on my phone and want to share it. Maybe replace the app icon?
openhab-xxxhdpi

### PR DESCRIPTION
**Pull request by mueller-ma**
I added a square and a circle material icon. Google decided to introduce round icons in Android which can be used by a launcher (e.g. on Google's Pixel). Other devices see the square icon: https://developer.android.com/about/versions/nougat/android-7.1.html#circular-icons

Fixes #278

### CODE REVIEW

**Comment by mueller-ma** [comment]
We need API 25 to compile this. I disabled the round icons for now. When #281 is merged we can enable them

**Comment by digitaldan** [comment]
Those look great, thanks!  I will revisit #281 this weekend.

**Comment by digitaldan** [comment]
@kaikreuzer I think these look great but wanted to make sure you are ok with the look and feel here.

**Comment by kaikreuzer** [comment]
It resembles the style that I chose for docs.openhab.org, so I probably cannot argue against it ;-)

**Comment by digitaldan** [comment]
Sounds great.  I am blocked on our cloudbees config for #281 , but I have finally made some progress, as soon as I get that fixed I will test this out.

**Comment by mueller-ma** [comment]
@digitaldan Let me test my merge first

**Comment by mueller-ma** [comment]
@digitaldan My Android Studio changed the gradle dependency, but it works

**Comment by mueller-ma** [comment]
I reopen a PR with just one commit

**Pull request closed without merging**
