### PR TITLE
Display correct icon for dimmer items controlled by a switch

### LINKED ISSUE #307: Wrong icon displayed for a Switch element linked to a Dimmer item
Here is the item:
```
Dimmer LampeChambre "Lumière dans la chambre [%d %%]" <dimmablelight> {mios="unit:house,device:510/service/Dimming1/LoadLevelStatus", autoupdate="false"}
```
Here is a part of the sitemap:
```
		Text item=GEclairage {
			Switch item=LampeChambre icon="light"
		}
```
The switch state is perfectly updated (OFF or ON) but the icon is always unchanged, a light ON, even when the light status is OFF.

### PR DESCRIPTION
**Pull request by mueller-ma**
Fix #307

### CODE REVIEW

**Comment by lolodomo** [comment]
Please consider any value greater than 0 as ON and not only 100.

**Comment by mueller-ma** [comment]
Can a switch set a dimmer item to e.g. 10?

**Comment by lolodomo** [comment]
No but a dimmer item can be set to 10 for example.

**Comment by digitaldan** [comment]
LGTM

**Pull request merged**
