### PR TITLE
Handle volume Up/Down buttons

### PR DESCRIPTION
**Pull request by eschava**
Volume up/down buttons are handled by first slider/setpoint widget on current frame

### CODE REVIEW

**Comment by cribskip** [comment]
Does this harmonate together with the dynamic sitemap handling? 

Thanks for the feature, thought about it also several times😊

**Comment by eschava** [comment]
Unfortunately I cannot find how dynamic visibility is handled by android app. Maybe hidden items are just not present in the frame so it should work OK in this case

**Comment by kaikreuzer** [comment]
Dynamic visibility is handled on server side, not on client side. So for HABDroid, they hidden widgets are just as if they didn't exist.

**Comment by belovictor** [comment]
I've integrated this feature manually, thank you very much for your contribution!

**Pull request closed without merging**
