### PR TITLE
Fetch icons from correct path for OH2

### LINKED ISSUE #145: Icons don't update on openHAB 2
The app still expects a string like "rollershutter-40" as an icon parameter in the sitemap.
In openHAB 2, this has been split into icon and state now - so you only receive "rollershutter" as the icon and you will have "40" as the state.
From this, the HTTP request has to be assembled like in the past as 'icon/rollershutter-40.png' or alternatively (recommended!) as 'icon/rollershutter?state=40&format=png'.

See https://www.eclipse.org/smarthome/documentation/features/ui/icons.html#icon-servlet for details.

### PR DESCRIPTION
**Pull request by hazzeh**
When using OpenHAB2, fetch icons from the ESH icon servlet.
Add an abstract method getIconPath() to OpenHABWidget and
OpenHABSitemap that will fetch the correct path for the
server side icon, it will behave differently depending on
OpenHAB version.

Use factory method when creating OpenHABWidgets instead of
a constructor.

Add testCompile dependency to org.json to be able to stub
JSONObject.

Fixes #145

Signed-off-by: Hans Hazelius <hans@hazelius.se>

### CODE REVIEW

**Comment by kaikreuzer** [comment]
@hazzeh You're my hero - I have waited for this fix for so long :-)

**Comment by hazzeh** [comment]
I'm still missing some icons in my sitemap, but they seems to be missing in org.openhab.ui.iconset.classic. For example "socket".

**Comment by digitaldan** [comment]
@hazzeh testing looks good on my OH2 install and on demo.openhab.org, I'll run it on a few more devices tonight.  Is this ready to merge or do you need to look the missing icon (socket) issue?

**Comment by hazzeh** [comment]
@digitaldan it is ready for merge. The missing icon is due to something in my local OH2 installation.

**Comment by digitaldan** [comment]
Awesome, thanks.

**Pull request merged**
