### PR TITLE
Add basicui-like themes

### PR DESCRIPTION
**Pull request by mueller-ma**
This PR adds a bright and a dark theme that have the same colorset than the basic ui.
I also changed the button color from colorPrimary to colorAccent. This does not make a difference in the old themes, but in the basic ui theme the buttons are pink.
If the method setActivityTheme failes to resolve the string, it defaults to the default theme. (That happend once, fix is in #292, but it may happen again and than we are save)
I replace some hex codes in themes.xml with color tags.

#300 also applies here.

screenshot_1504780800
screenshot_1504781287
screenshot_1504781314

Signed-off-by: mueller-ma <mueller-ma@users.noreply.github.com>

### CODE REVIEW

**Comment by mueller-ma** [comment]
Can be merged.
Tested on several devices.

**Comment by mueller-ma** [comment]
Here is some feedback: https://community.openhab.org/t/basic-ui-like-themes-for-android-app/34208

**Comment by digitaldan** [comment]
LGTM!

**Comment by mueller-ma** [comment]
People in the poll voted for "I really like it, the bright one should be the default theme", but I see a problem. The openhab color is orange, so I woulnd change the icon color, but than we would have a orange icon that starts a blue/pink app.
So I would leave the orange theme as default.

**Pull request merged**
