### PR TITLE
Remove Bindings and Discovery funtionality from app

### LINKED ISSUE #392: Remove "side menu" from the app
In a rush of adding support for openHAB 2, Victor had introduced the side menu in the app as a first start, which adds "Discovery" and "Binding" menus - the implementation has been left very rudimentary though since then and I doubt that they are being used by anyone.

What is more, to not have such an empty menu with just 2 entries, the sitemaps were added there as well as an alternative way to setting them in the configuration. This is actually pretty counterproductive, because it leads people to believe that they should/could use sitemaps as a navigational element, to quickly switch between them. Instead, their intended use is to be set in the configuration and not to be changed by the user.

### PR DESCRIPTION
**Pull request by FlorianSW**
Fixes #392

### CODE REVIEW

**Comment by mueller-ma** [comment]
@FlorianSW Can you change the mail address in this commit or add it to your github account?

**Comment by mueller-ma** [comment]
Did you check if other drawer entries still work as expected. I dont see why they shouldn't work, but just to be sure.

**Comment by mueller-ma** [comment]
Can you remove all screenshots of that features?

**Comment by digitaldan** [comment]
I can confirm sitemap selection works and the notification menu shows up if enabled.

**Pull request merged**
