### PR TITLE
Update to latest API+tools+gradle+misc.  (try #2)

### PR DESCRIPTION
**Pull request by fat-tire**
A re-do of #268 - Hope this works better.

### CODE REVIEW

**Comment by digitaldan** [comment]
I'm going to try this today, sorry about the long delay.

**Comment by digitaldan** [comment]
FYI, I'm still have troubles with accepting sdk licenses on our cloud bees instance , as soon as I fix that we should be good

**Comment by digitaldan** [comment]
Hurray!  I finally fixed our build issues.  Can you fix the conflict that has emerged from other PR's being merged?  As soon as that is done I will finally be able to merge this one. Thanks for your patience.

**Comment by digitaldan** [comment]
I went ahead and fixed the conflict, merging.

**Comment by mueller-ma** [comment]
@fat-tire  The Readme says "...and install Android SDK version 4.0.3"

**Pull request merged**
