### PR TITLE
OpenHAB for Android Wear

### PR DESCRIPTION
**Pull request by tobiasamon**
Hi,

in this branch I have created a UI for Android Wear. In the main openhab app a service is started which communicates with the wearable device.

At the moment it does not support openhab 2. The support is about to be implemented soon.

If there is any open issue, feel free to contact me.

best regards
Tobias

### CODE REVIEW

**Comment by belovictor** [comment]
Can you please squash it into a single commit please?

**Comment by tobiasamon** [comment]
OK... there are now 2 commits. One with all my changes and the second with the merge of the current master, so there are no conflicts.

**Comment by belovictor** [comment]
@tobiasamon , sorry, but pull request must be against current master and only include the changes for Wear UI.

**Comment by tobiasamon** [comment]
Actually all changes are required by the wear extension. And the pull request is against current master.

**Comment by digitaldan** [comment]
Hi @tobiasamon,  an Android Wear client sounds awesome.  Is this something you are interested in maintaining going forward?

**Comment by dustinthurston** [comment]
I haven't had any luck installing this. I tried installing the over the play version and the cloudbees download. When I attempt to install, it attempts to install as an update to Habdroid, then returns a message of "App not installed".

**Comment by digitaldan** [comment]
closing due to inactivity

**Pull request closed without merging**
