### PR TITLE
Refreshed images should have authorization.

### PR DESCRIPTION
**Pull request by slawekjaranowski**
When image or chart is refreshed should has authorization.

### CODE REVIEW

**Comment by digitaldan** [comment]
Hi @slawekjaranowski , thanks (again).  I'll try and get this pulled down soon for testing.  From looking at the changes you made, authentication was being set on the initial request but not when the refresh handler was triggering a request, is this correct?

**Comment by slawekjaranowski** [comment]
Yes, only first request has authorization, requests from handler don't have it.

**Comment by digitaldan** [comment]
hi @slawekjaranowski, looks good so far. I found one issue where the refresh timer didn't get canceled when my device auto locked (the rest of the app did pause), and it ended up running all night.  I'm not sure if this is an existing issue or related to your changes, do you have any thoughts?  My guess is it's an existing issue, but can you take another look just to be sure?

**Comment by slawekjaranowski** [comment]
Hi, I think that is existing issue `cancelRefresh` method in `MySmartImageView` is called from `OpenHABWidgetAdapter`.

I don't see way to recreate `imageRefreshTimer` from class `MySmartImageView`.

One place where I see that application don't stop after `onPause` method is `OpenHABWidgetListFragment`.
`OpenHABWidgetListFragment.onPause` call `mRequestHandle.cancel` but when  request is during processing can cause some interrupt errors which is handled by `mRequestHandle.onFailure` or `processContent` and call again `showPage` which create new  `mRequestHandle`.
And after this processing is not stopped.

**Comment by digitaldan** [comment]
Ok thanks, I'll take a look. It might be as simple as checking if the mRequestHandle is null or canceled when calling show page in the onFailure callback.

**Pull request merged**
