### PR TITLE
Fix overlapping label and item text/buttons

### LINKED ISSUE #435: Label and item text overlap when label is too long
Same as #121, but for Selection, Switch without mappings, setpoint, text, slider, rollershutter

### PR DESCRIPTION
**Pull request by mueller-ma**
This is the same than #390, but for all other elements.
I changed the relative layouts to constraint layouts.

Fixes #435

After:
screenshot_2017-10-30-19-23-03
screenshot_2017-10-30-19-23-06

Sitemap:
```
        Selection item=number4 label="hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhdddddddddddddddddddddddddddddddddddddddddddddddddddddddddhhhhaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaahhhhh" mappings=[1="foo", 2="bar"]
        Switch item=number4 label="hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhdddddddddddddddddddddddddddddddddddddddddddddddddddddddddhhhhaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaahh" mappings=[1="foo", 2="bar"]
        Switch item=number4 label="hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhdddddddddddddddddddddddddddddddddddddddddddddddddddddddddhhhhaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaahh"
        Setpoint item=number4 label="hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhdddddddddddddddddddddddddddddddddddddddddddddddddddddddddhhhhaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaahhhh[%d]"
        Text item=number4 label="hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhdddddddddddddddddddddddddddddddddddddddddddddddddddddddddhhhhhhhhaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa[%d]"
        Slider item=number4 label="hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhdddddddddddddddddddddddddddddddddddddddddddddddddddddddddhhhhhhhhaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa[%d]"
        Default item=color1 label="hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhdddddddddddddddddddddddddddddddddddddddddddddddddddddddddhhhhhhhhaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa[%d]"
        Default item=roller1 label="hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhdddddddddddddddddddddddddddddddddddddddddddddddddddddddddhhhhhhhhaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa[%d]"
```
Would be great if someone could test this on another device.

Signed-off-by: mueller-ma <mueller-ma@users.noreply.github.com>

### CODE REVIEW

**Comment by mueller-ma** [comment]
@wrosenauer Can you test following apk: [mobile-debug.zip](https://github.com/openhab/openhab.android/files/1428334/mobile-debug.zip)

**Comment by ThomDietrich** [comment]
@mueller-ma thanks for solving the issue! Works as expected on my device.

**Comment by mueller-ma** [comment]
@ThomDietrich Which device do you have?

**Comment by ThomDietrich** [comment]
I've tested your attached app on a OnePlus 3 smartphone with android 7.
I have to add one bug report: If the value of an item (e.g. a string) is long, the label will be pushed out on the left. Can you do something about that?

**Comment by ThomDietrich** [comment]
I thought about the whole issue some more, especially for Text sitemap elements. You are currently leaving the value unchanged and are shortening the label. I'm not sure if this is ideal. The sitemap was hand build by the user and the label is something meaningful. Without it (after being replaced by just "..." in the worst case) the meaning of the value text might get unclear. 
I wonder if it would be a better solution for the Text element to scroll the value string if an overlap would occur. Is that easy to implement?

**Comment by mueller-ma** [comment]
I tought about implementing a max width for the text value, so it is always a few characters of the label shown.

**Comment by mueller-ma** [comment]
The text now scrolls:
screenshot_2017-10-31-19-58-00
[mobile-debug.zip](https://github.com/openhab/openhab.android/files/1431966/mobile-debug.zip)

**Comment by ThomDietrich** [comment]
Hey @mueller-ma,
doesn't seem to work as expected. See screenshot...

index

**Comment by mueller-ma** [comment]
I dont know why this is happening. Now the icon and the value are always shown and (if space) the label.
[mobile-debug.zip](https://github.com/openhab/openhab.android/files/1441769/mobile-debug.zip)

**Comment by ThomDietrich** [comment]
Same behavior. I'm also not so sure about the scrolling any more. It creates a lot of unwanted visual chaos.
Let's look at it differently: The sitemap is built by the end user and he/she has to make sure, that everything is in order. The case where a string is too long is hence really an exception. In this case it might be okay to just trim it down to a certain length, just as you do with the label for other element types currently.
At the end of the day the case where the app is forced to shorten strings will eventually be handled by the end user by manually shortening his/her strings to fit onto the screen.

**Comment by mueller-ma** [comment]
Ok, I will undo my last commit. I think the actuall value is more important than the label. If the label is not visible, the user should split it up in two text elements.

**Comment by mueller-ma** [comment]
Triggering travis

**Pull request merged**
