### PR TITLE
the entire row containing a switch acts as the switch

### PR DESCRIPTION
**Pull request by Human**

### CODE REVIEW

**Comment by belovictor** [comment]
I think this is not really a good idea cause I wanted to use clicks on items for openHAB 2.0 functionality (configuration, group assignment and so on)...

**Comment by xsnrg** [comment]
Given the comment and reasoning for not clicking the whole bar, this could probably be closed.

**Comment by zacharyyy** [comment]
@belovictor, why not do the configuration, assignment, etc in a contextual popup menu when a row is long pressed?

Then a single click on a row could act as a switch.

**Comment by digitaldan** [comment]
@Human as discussed in #90 I think this makes sense, are you able to fix the conflicts and re-submit?

**Comment by kaikreuzer** [comment]
> why not do the configuration, assignment, etc in a contextual popup menu when a row is long pressed?

I agree (and that's what MD UX asks for as well).

**Comment by digitaldan** [comment]
So I cleaned up the conflicts, and i think I see what the issue is, the way this is listening for widget presses is not compatible with how the rest of the app needs to listen for long widget presses (for the extras features mentioned above). This means switch widgets would lack the extra functionality that all other widgets have (we would be taking away functionality).   It's probably not hard to make it compatible, but will definitely require some more work.

**Comment by digitaldan** [comment]
Closing due to inactivity

**Comment by thjunge11** [comment]
I have the problem that the OnTouchListener does not work with any Android device that does not have touch input (like Android fire TV), so the App is kind of useless on these devices as you are not able to operate the swichh elements (and the others).

One could attach an OnClickListener in parallel to a onTouchListener to every clickable type and ignore the event if (isInTouchMode() == true).

What do you think? I would like to participate in coding here.

**Pull request closed without merging**
