### PR TITLE
Menu rework

### PR DESCRIPTION
**Pull request by mueller-ma**
This PR will

- [x] Add several icons with different resolutions
- [x] Translate "Voice Recognizition"
- [x] Disable NFC Menu entry, if no NFC is available (will need help for this)
- [x] Reorder menu entries
- [x] Show NFC in the action bar
- [x] Apply material typing to strings

### CODE REVIEW

**Comment by digitaldan** [comment]
Hi, can you explain what issue(s) this PR is resolving?  Thanks!

**Comment by mueller-ma** [comment]
If you dont have the voice recognition the action bar is empty. So why not move an entry from the menu to the action bar.
"Settings" is usually the last entry, so I moved it.

**Comment by digitaldan** [comment]
@mueller-ma can you resolve the merge conflicts that have come up?  Thanks.

**Comment by digitaldan** [comment]
LGTM,  I'll merge as soon as the conflicts are resolved.

**Comment by mueller-ma** [comment]
Can you merge #352 first? I think that might introduce new confilcts

**Comment by digitaldan** [comment]
Done

**Comment by mueller-ma** [comment]
Can someone test, if nfc is visible when the phone supports it?

**Comment by mueller-ma** [comment]
I also made the select sitemap dialog non cancelable, when no sitemap is in the shared preference

**Comment by digitaldan** [comment]
I took the day off from work so I can review OH PR's :-)   I'll take a look today.

**Comment by digitaldan** [comment]
>Show NFC in the action bar
So this is not something I use, so can you help me understand why we need this in the action bar?  I believe this button is used to associate an nfc tag with an item, so it's something you setup a few times, but then would not use again unless adding a new tag.  Since its a setup function of the app, and not something to be used a part of the regular user flow, I don't think it should be on the action bar.

**Comment by mueller-ma** [comment]
Ah ok, I dont use this either. I move it back to the menu

**Comment by mueller-ma** [comment]
Wait. With my last merge I mixed up my branches

**Comment by mueller-ma** [comment]
I dont really know how I can remove 307-dimmer-switch-icon, that changes mobile/src/main/java/org/openhab/habdroid/model/OpenHAB2Widget.java

**Comment by digitaldan** [comment]
@mueller-ma do you need something from me or are you resolving yourself?

**Comment by mueller-ma** [comment]
If you dont matter, we could fix two issues in one PR

**Comment by mueller-ma** [comment]
I'll make a clean new PR

**Pull request closed without merging**
