### PR TITLE
Add foss build flavor

### PR DESCRIPTION
**Pull request by mueller-ma**
See #30 
I have moved non free components to mobile/src/full/java/org/openhab/habdroid and create dummy classes  and functions in mobile/src/foss/java/org/openhab/habdroid.

Of course this breaks cloud functionality for foss user.

### CODE REVIEW

**Comment by digitaldan** [comment]
How would we support a foss build going forward, would we need to build and sign a f-droid version and deploy to that platform for every release?

**Comment by mueller-ma** [comment]
No, fdroid builts are automated. I will some metadata about this app to the fdroid metadata repo and than a new version will be automaticly built, when you create a new tag. I have to look at the docs, maybe a version bump in the android manifest is enough.

**Comment by digitaldan** [comment]
@mueller-ma can you resolve the conflict issues and I can merge?  Also I think we want to remove google analytics from the project as we really don't use it.  We also need to remove the critterism stuff and replace it with the Google supplied crash reporting.  Maybe something you want to try out.

**Comment by mueller-ma** [comment]
I think I will first make a pr to remove that stuff, then try to integrate the google crash analytics and then make a foss flavor

**Comment by mueller-ma** [comment]
On fdroid only specific maven repos are allowed. Since the only depency from the oh repo was smart-image-view I changed it to the github repo.
Now I get following error:
```
Error:Error converting bytecode to dex:
Cause: Dex cannot parse version 52 byte code.
This is caused by library dependencies that have been compiled using Java 8 or above.
If you are using the 'java' gradle plugin in a library submodule add 
targetCompatibility = '1.7'
sourceCompatibility = '1.7'
to that submodule's build.gradle file.
...while parsing com/loopj/android/image/BitmapImage.class
```

**Comment by mueller-ma** [comment]
Works now. Can someone test if openhab cloud still works as expected in the full build?

**Comment by mueller-ma** [comment]
The versions of the foss build are called 1.8.0.8-foss, so both versions can be installed.

**Comment by digitaldan** [comment]
Hi @mueller-ma , in android studio it looks like it is running the foss version by default , do you know how to configure that so it runs the non foss version?

**Comment by mueller-ma** [comment]
On the left sidebar there should be an entry with the green android logo. Click on it and a windows pops up where you can switch between foss and full

**Comment by digitaldan** [comment]
Found it, thanks!

**Comment by digitaldan** [comment]
I don't think device registration is working with myopenhab.org.  I have not looked to much into it, but my test device is not registering with the non foss build.

**Comment by digitaldan** [comment]
wait!  This could be my setup, I had my credentials entered when testing the foss version, but forgot when switching to the non foss one, i needed to re-enter them.

**Comment by digitaldan** [comment]
Nope, still not working.  Can you setup an account on myopenhab.org and test?  You don't actually need to hook up an openhab, there is a "devices" menu that shows registered mobile devices which also has the ability to send a test message to them.

**Comment by mueller-ma** [comment]
Well, I have removed all gcm methods with dummy methods, so I think openhab cloud wont work.

**Comment by mueller-ma** [comment]
Ah, you tested the full built. I will look into that

**Comment by mueller-ma** [comment]
I connected my oh with myopenhab.org and tried with a build from current master branch. The device registered gcm as I can send messages to it.
After that I pruged the app data and tried with the full build from this PR to send messages => also worked.

**Comment by mueller-ma** [comment]
Ok, initial registration is not working.

**Comment by mueller-ma** [comment]
Reopend in #455

**Pull request closed without merging**
