### PR TITLE
Fixed WebView problem

### PR DESCRIPTION
**Pull request by bodiroga**
Fixed WebView widgets loading problem when security is ON (issues #127 and #43

### CODE REVIEW

**Comment by kaikreuzer** [comment]
Assuming @belovictor approves this PR, could you please make sure that you squash your commits into one?

**Comment by belovictor** [comment]
Strangely it includes commits from another pull request which is about wearable support. So can you please clean it up down to webview fix please?

**Comment by belovictor** [comment]
Ok, I extracted the fix from this PR and applied it.

**Comment by eschizoid** [comment]
@belovictor this is still happening on iOS version 1.7.1. Should I create a ticket for this or you want to reopen this one?

**Comment by sujitrp** [comment]
Still I am getting webview issue over mobile app @2.3

**Comment by mueller-ma** [comment]
What kind of issues?

**Pull request closed without merging**
