### PR TITLE
Video: fix #402

### LINKED ISSUE #402: Video element: add support for HTTP Live Streaming playlist
Please add support for HTTP Live Streaming playlist.
As it is working in Chrome on Android, I suppose it could work in the app too.
You can see how it was easy to update Basic UI and Classic UI: https://github.com/eclipse/smarthome/pull/4386
The general idea is to bypass the proxying and to use a particular media type.

### PR DESCRIPTION
**Pull request by lolodomo**
Fixes #402

Signed-off-by: Laurent Garnier <lg.hc@free.fr>

### CODE REVIEW

**Comment by mueller-ma** [comment]
Doesn't this also implement the video item with the url as state, but only when encoding is hls?

**Comment by lolodomo** [comment]
Nothing changed when encoding different from HLS. In this case, the URL is provided by the  proxy using the proxy URL returned by the REST API. The proxy uses the item value as URL if set or by default the value of the URL element in the video sitemap element.

**Comment by mueller-ma** [comment]
When you remove the check for the encoding wouldn't it fix items like
`Video item=foo url=http://....`?

**Comment by lolodomo** [comment]
Case with `Video item=foo url=http://....`remains unchanged and should work as before in app. Do you mean that there is a problem in such a case ? I don't see any issue reported. Note that I opened yesterday another issue relative to support of video URLs.
My current PR is clearly only to fix the behaviour when and only when encoding is set to HLS. Other cases remains unchaned.

**Comment by lolodomo** [comment]
@digitaldan : can this PR be reviewed ? We need for Netatmo Welcome camera.

**Pull request merged**
