### PR TITLE
Feature read notifications

### PR DESCRIPTION
**Pull request by cribskip**
This will read aloud notifications sent by sendNotification, partially enabling what #93 requested.
If media volume is muted, this will not read what's sent to respect user's privacy.

usage: sendNotifaction("speak Somebody opened the frontdoor.")
Text after "speak" will be spoken and this will be displayed in the notification.

Note aside: I stumbled across that GCM introduces a whitespace in the beginning of a notification.

### CODE REVIEW

**Comment by belovictor** [comment]
This is cool, I would propose to change it a little bit though. Let's use another event for spoken notifications. I will create a separate method in my.openHAB bundle and in the cloud which will be forwarded to Android app and will be spoken instead of showing in notifications. GCM messages from my.OH have a field named 'type' which has value of 'notification'. We can use 'speak' instead. Can you rewrite the code for that?

**Comment by cribskip** [comment]
Sounds nice, will do when I find time. 

Maybe two functions are sensible: speak and show-and-speak. This would prevent double transmits and save traffic for mobile data plans.

Btw, I saw sendNotification supports icons but habdroid doesn't. Shall I create an issue?

**Comment by belovictor** [comment]
No, not yet. It's not clear yet where it should load those icons from :-)

**Comment by cribskip** [comment]
I updated my branch and quickly tested with the emulator, worked just fine.

**Comment by cribskip** [comment]
I will have to rebuild everything, syncing turned out something about gradle.
Shall I create a new pull request when done?

Sascha

**Comment by digitaldan** [comment]
@cribskip  My guess is that the work needed in my.openhab has been put on hold.  What would you like to do with this PR?

**Comment by digitaldan** [comment]
Closing due to inactivity.

**Pull request closed without merging**
